frågor = {"Vilken symbol används för att starta en kommentar?" : "#",
             "Vad är nyckelordet för att definiera en funktion i python?" : "def",
             "Vilken funktion används för att skriva ut saker på skärmen?" : "print",
             "Hur tar man fram längden på listan i variabeln 'fruits'?" : "len",
             "Vad heter nyckelordet för att göra en loop i Python?" : "for",
             "Hur får man tillgång till ett enskilt objekt på listan?": "index",
             "Vilken operatör returnerar heltalets återstod (modulo) av divisionen?": "%",
             "Hur kan du kontrollera objektets typ?":"type()",
             "Vad heter behållare för lagring av datavärden?":"variabel",
             "Hur skriver man datatypen för ett helt tal?":"int"}